"""Add donation history and donor location

Revision ID: 2509a68b6841
Revises: 13daa5450e19
Create Date: 2026-07-13 14:34:45.224879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2509a68b6841'
down_revision: Union[str, Sequence[str], None] = '13daa5450e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('blood_request_id', sa.Integer(), nullable=True),
    sa.Column('hospital_name', sa.String(length=255), nullable=False),
    sa.Column('units_donated', sa.Integer(), nullable=False),
    sa.Column('donated_at', sa.DateTime(), nullable=False),
    sa.Column('verified_by_hospital', sa.Boolean(), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['blood_request_id'], ['blood_requests.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_history_id'), 'donation_history', ['id'], unique=False)
    op.add_column('donor_profiles', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('donor_profiles', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_column('donor_profiles', 'last_donation_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donor_profiles', sa.Column('last_donation_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('donor_profiles', 'longitude')
    op.drop_column('donor_profiles', 'latitude')
    op.drop_index(op.f('ix_donation_history_id'), table_name='donation_history')
    op.drop_table('donation_history')
    # ### end Alembic commands ###
